name: deploy on push
on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-lastest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v3
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrects.SHH_USER_NAME}}
          port: ${{secrects.SHH_PORT}}
          key: ${{secrects.SHH_KEY}}
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1